import { defineConfig } from 'vite'
import {resolve} from 'path'
import vue from '@vitejs/plugin-vue';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  build: {
    lib: {
      entry: resolve(__dirname, "src/index.ts"),
      name: "ComponentLibrary",
      fileName: (format) => `library.${format}.js`,
    },
    rollupOptions: {
      external: ['vue', 'vue-router', 'vuex'],
      output: {
        exports: 'named',
      	globals: {
      	  vue: "Vue"
      	}
      }
    },
    emptyOutDir: false, // to retain the types folder generated by tsc
  },
  resolve: {
    alias: [
      {
        find: /^@\/(.+)/,
        replacement: `${resolve(__dirname, 'src')}/$1`
      }
    ]
  },
  
})
